# Use latest stable release of docker syntax.
# syntax=docker/dockerfile:1

#==============================================================================#
#========= Base Image =========#
#==============================================================================#
# Use slim, up to date, and official LTS version as base.

# ARG NODE_VERSION=20.9.0
ARG NODE_VERSION=21.7.1
# Uses an official Node.js slim image as the base
FROM node:${NODE_VERSION}-bookworm-slim AS base

# Declaring the port the app runs on
#ENV PORT=3000

# Setting up the environment for pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Enabling Corepack to manage package managers like pnpm
RUN corepack enable

# Set the working directory for all stages
WORKDIR /workspace/next-app

RUN echo "Base image build successfully"


#==============================================================================#
#========= Production Dependancy Image =========#
#==============================================================================#

FROM base AS prod-deps

# Copying package.json and pnpm-lock.yaml for dependency installation
# COPY /next-app/package.json /next-app/pnpm-lock.yaml ./
COPY /next-app/package.json ./

# Installing production dependencies without updating the lockfile
# RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod

RUN echo "Dependancy image build successfully"


#==============================================================================#
#========= Development Image =========#
#==============================================================================#

FROM base AS dev

# Specify environment
ENV NODE_ENV=development

# Installing git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Copying installed node_modules for production dependencies
COPY --from=prod-deps /workspace/next-app/node_modules /workspace/next-app/node_modules

# Copying package.json and pnpm-lock.yaml for dependency installation
#COPY /next-app/package.json /next-app/pnpm-lock.yaml ./
COPY /next-app/package.json ./

# Install all dependencies (will reuse production dependencies)
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

EXPOSE 3000

RUN echo "Development image build successfully"
