version: '3'

services:

  frontend-prod:
    container_name: bookscanner-frontend-prod
    image: reinhuddev1/frontend:main
    pull: always
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"

  backend-prod:
    container_name: bookscanner-backend-prod
    image: reinhuddev1/backend:main
    pull: always
    env_file:
      - ./backend/prod.env
    restart: always
    ports:
      - "8000:8000"
