version: '3'

services:

  frontend:
    container_name: frontend

    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    
    restart: always

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    environment:
      - NODE_ENV=dev
      
    volumes:
      - .:/workspace:cached
    
    ports:
      - ${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}

    expose:
      - ${FRONTEND_HOST_PORT}


  backend:
    container_name: backend

    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev 

    env_file:
      - ./backend/.env
    
    restart: always

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
      
    volumes:
      - .:/workspace:cached

    expose:
      - "8080"